@startuml

interface Worker {
  + number id
  + string firstName
  + string lastName
  + string job?
}

interface Construction {
  + number id
  + string name?
  + string address
  + Date endDate?
}

@enduml